# Generated by Django 5.1.3 on 2024-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
