# Generated by Django 5.1.3 on 2024-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0003_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_color',
            field=models.CharField(default='#FFA500', max_length=7),
        ),
    ]
